from pydantic import BaseModel

class BlogState(BaseModel):
    # User Input 
    topic : str = "" # Which topic is to be generated by AI
    audience : str = "general people" #Programmers, Developers , Doctors etc
    requirements: str = "" # Format, length, tone, or other mandatory user instructions

    # Researcher Output
    research: str = ""
    research_feedback: str = "" # By user
    
    # Writer Output
    draft: str = ""
    draft_feedback: str = "" # By user
    
    
    # Editor Output
    final_blog : str = ""
    
    # Metadata
    revision_count :int = 0 # User has limit for feedback
    
